requires = {};

dependencies = {
   ".":{
      "context":"dkit-reader",
      "baseUrl":".",
      "packages":[
         {
            "name":"sequelize-port",
            "location":"node_modules/sequelize-port",
            "main":"index"
         }
      ]
   },
   "node_modules/url":{
      "context":"url",
      "baseUrl":"node_modules/url",
      "packages":[
         {
            "name":"querystring",
            "location":"node_modules/url/node_modules/querystring",
            "main":"querystring"
         },
         {
            "name":"punycode",
            "location":"node_modules/url/node_modules/punycode",
            "main":"punycode"
         }
      ],
      "main":"url"
   },
   "node_modules/url/node_modules/punycode":{
      "context":"punycode",
      "baseUrl":"node_modules/url/node_modules/punycode",
      "packages":[

      ],
      "main":"punycode"
   },
   "node_modules/url/node_modules/punycode/vendor/qunit":{
      "context":"qunit",
      "baseUrl":"node_modules/url/node_modules/punycode/vendor/qunit",
      "packages":[

      ],
      "main":"qunit/qunit"
   },
   "node_modules/url/node_modules/querystring":{
      "context":"querystring",
      "baseUrl":"node_modules/url/node_modules/querystring",
      "packages":[

      ],
      "main":"querystring"
   },
   "node_modules/sequelize-port":{
      "context":"sequelize",
      "baseUrl":"node_modules/sequelize-port",
      "packages":[
         {
            "name":"mysql",
            "location":"node_modules/mysql",
            "main":"index"
         },
         {
            "name":"underscore",
            "location":"node_modules/underscore",
            "main":"underscore"
         },
         {
            "name":"underscore.string",
            "location":"node_modules/underscore.string",
            "main":"lib/underscore.string"
         },
         {
            "name":"lingo",
            "location":"node_modules/lingo",
            "main":"index"
         },
         {
            "name":"moment",
            "location":"node_modules/moment",
            "main":"moment"
         },
         {
            "name":"buffer",
            "location":"node_modules/buffer",
            "main":"index"
         },
         {
            "name":"commander",
            "location":"node_modules/sequelize-port/node_modules/commander",
            "main":"index"
         },
         {
            "name":"generic-pool",
            "location":"node_modules/generic-pool",
            "main":"lib/generic-pool"
         },
         {
            "name":"util",
            "location":"node_modules/util",
            "main":"util"
         },
         {
            "name":"events",
            "location":"node_modules/events",
            "main":"events"
         }
      ],
      "main":"index"
   },
   "node_modules/sequelize-port/node_modules/generic-pool":{
      "context":"generic-pool",
      "baseUrl":"node_modules/sequelize-port/node_modules/generic-pool",
      "packages":[

      ],
      "main":"lib/generic-pool"
   },
   "node_modules/sequelize-port/node_modules/events":{
      "context":"events",
      "baseUrl":"node_modules/sequelize-port/node_modules/events",
      "packages":[

      ],
      "main":"events"
   },
   "node_modules/sequelize-port/node_modules/lingo":{
      "context":"lingo",
      "baseUrl":"node_modules/sequelize-port/node_modules/lingo",
      "packages":[

      ],
      "main":"index"
   },
   "node_modules/sequelize-port/node_modules/util":{
      "context":"util",
      "baseUrl":"node_modules/sequelize-port/node_modules/util",
      "packages":[

      ],
      "main":"util"
   },
   "node_modules/sequelize-port/node_modules/buffer":{
      "context":"buffer",
      "baseUrl":"node_modules/sequelize-port/node_modules/buffer",
      "packages":[

      ],
      "main":"index"
   },
   "node_modules/sequelize-port/node_modules/mysql":{
      "context":"mysql",
      "baseUrl":"node_modules/sequelize-port/node_modules/mysql",
      "packages":[
         {
            "name":"require-all",
            "location":"node_modules/sequelize-port/node_modules/mysql/node_modules/require-all",
            "main":"index"
         }
      ],
      "main":"index"
   },
   "node_modules/sequelize-port/node_modules/mysql/node_modules/require-all":{
      "context":"require-all",
      "baseUrl":"node_modules/sequelize-port/node_modules/mysql/node_modules/require-all",
      "packages":[

      ],
      "main":"index"
   },
   "node_modules/sequelize-port/node_modules/moment":{
      "context":"moment",
      "baseUrl":"node_modules/sequelize-port/node_modules/moment",
      "packages":[

      ],
      "main":"moment"
   },
   "node_modules/sequelize-port/node_modules/commander":{
      "context":"commander",
      "baseUrl":"node_modules/sequelize-port/node_modules/commander",
      "packages":[

      ],
      "main":"index"
   },
   "node_modules/sequelize-port/node_modules/underscore":{
      "context":"underscore",
      "baseUrl":"node_modules/sequelize-port/node_modules/underscore",
      "packages":[

      ],
      "main":"underscore"
   },
   "node_modules/sequelize-port/node_modules/underscore.string":{
      "context":"underscore.string",
      "baseUrl":"node_modules/sequelize-port/node_modules/underscore.string",
      "packages":[

      ],
      "main":"lib/underscore.string"
   },
   "node_modules/sequelize-port/node_modules/q":{
      "context":"q",
      "baseUrl":"node_modules/sequelize-port/node_modules/q",
      "packages":[

      ],
      "main":"q"
   },
   "node_modules/sequelize-port/node_modules/validator":{
      "context":"validator",
      "baseUrl":"node_modules/sequelize-port/node_modules/validator",
      "packages":[

      ],
      "main":"validator"
   },
   "node_modules/remedial":{
      "context":"remedial",
      "baseUrl":"node_modules/remedial",
      "packages":[

      ],
      "main":"index"
   },
   "node_modules/sequelize-port/node_modules/fs":{
      "context":"fs",
      "baseUrl":"node_modules/sequelize-port/node_modules/fs",
      "packages":[

      ],
      "main":"fs"
   },
   "node_modules/util":{
      "context":"util",
      "baseUrl":"node_modules/util",
      "packages":[
         {
            "name":"events",
            "location":"node_modules/events",
            "main":"events"
         }
      ],
      "main":"util"
   },
   "node_modules/fs":{
      "context":"fs",
      "baseUrl":"node_modules/fs",
      "packages":[

      ],
      "main":"fs"
   },
   "node_modules/path":{
      "context":"path",
      "baseUrl":"node_modules/path",
      "packages":[

      ],
      "main":"path"
   },
   "node_modules/sequelize-port/node_modules/path":{
      "context":"path",
      "baseUrl":"node_modules/sequelize-port/node_modules/path",
      "packages":[

      ],
      "main":"path"
   },
   "node_modules/request":{
      "context":"request",
      "baseUrl":"node_modules/request",
      "packages":[

      ],
      "main":"request"
   },
   "node_modules/util/node_modules/events":{
      "context":"events",
      "baseUrl":"node_modules/util/node_modules/events",
      "packages":[

      ],
      "main":"events"
   },
   "node_modules/underscore":{
      "context":"underscore",
      "baseUrl":"node_modules/underscore",
      "packages":[

      ],
      "main":"underscore"
   },
   "node_modules/requirejs":{
      "context":"requirejs",
      "baseUrl":"node_modules/requirejs",
      "packages":[

      ],
      "main":"bin/r"
   },
   "node_modules/q":{
      "context":"q",
      "baseUrl":"node_modules/q",
      "packages":[

      ],
      "main":"q"
   }
};
